---
framework: jest
tier: large
parallelism: 2
splitMode: file
preRun:
     command:
        - yarn install --dev
preMerge:
  env:
     FULL_TEST: true
     PRETTIER_FALLBACK_RESOLVE: true
  pattern:
    - "./tests/integration/__tests__/*.js"
    - "./tests/format/**/*.spec.js"
postMerge: 
  env:
     FULL_TEST: true
     PRETTIER_FALLBACK_RESOLVE: true
  pattern: 
    - "./tests/integration/__tests__/*.js"
    - "./tests/format/**/*.spec.js"
postRun:
     command:
        - yarn --version
version: 1.2
